### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by YuanHuiJuan** [punjabinuclei/RealTimeBatteryMonitoringSystem#1]
Could you please provide the training data? I'd like to replicate your code, but I don't have the appropriate dataset.

**Comment by punjabinuclei** [comment]
I apologize, but we are unable to share our training dataset at this time. However, I suggest using the [VTOL Battery Dataset](https://www.nature.com/articles/s41597-023-02180-5) , which we previously employed to evaluate our algorithms and system setup.
